name = "youtube-issue-worker"
main = "worker.js"
compatibility_date = "2025-01-01"
account_id = "6ca82b5f61c22dc2a98d85fa53dbcc6d"

[vars]
# YOUTUBE_API_KEY는 wrangler secret으로 설정하세요.
YOUTUBE_API_KEY = ""
