name = "yt-feed-hub-cron"
main = "cron-worker.js"
compatibility_date = "2025-01-01"

kv_namespaces = [
  { binding = "YT_CACHE", id = "5ca0820dbaa848fe9a3a04bdcc2a3be0" }
]

[triggers]
# Every 3 hours (UTC): 00,03,06,09,12,15,18,21
crons = ["0 */3 * * *"]
